import 'package:cloud_firestore/cloud_firestore.dart';

final dummyRecipes = [
  {
    "id": "r1",
    "title": "Classic Spaghetti Bolognese",
    "description":
        "A hearty Italian pasta dish with rich tomato and beef sauce.",
    "instructions": [
      "Cook pasta in salted water.",
      "Sauté onions and garlic.",
      "Add ground beef and brown.",
      "Pour in tomato sauce and simmer.",
      "Mix pasta with sauce and serve with parmesan.",
    ],
    "prep_time": 15,
    "cook_time": 45,
    "total_time": 60,
    "difficulty": "Medium",
    "servings": 4,
    "tags": ["Italian", "Dinner", "Pasta"],
    "categories": ["Main Course"],
    "ingredients": [
      {"name": "Spaghetti", "quantity": 400, "unit": "g", "optional": false},
      {"name": "Ground beef", "quantity": 500, "unit": "g", "optional": false},
      {"name": "Onion", "quantity": 1, "unit": "pc", "optional": false},
      {"name": "Garlic cloves", "quantity": 2, "unit": "pc", "optional": false},
      {
        "name": "Tomato sauce",
        "quantity": 500,
        "unit": "ml",
        "optional": false,
      },
      {"name": "Olive oil", "quantity": 2, "unit": "tbsp", "optional": false},
    ],
    "image_urls": [
      "https://www.kitchensanctuary.com/wp-content/uploads/2019/09/Spaghetti-Bolognese-square-FS-0204.jpg",
      "https://vikalinka.com/wp-content/uploads/2020/03/Spaghetti-Bolognese-13-Edit.jpg",
    ],
    "created_by": "p75y1GigXochokLkpQuZ7NwuUe42",
    "created_at": Timestamp.now(),
    "updated_at": Timestamp.now(),
    "nutrition": {"calories": 650, "protein": 35, "carbs": 60, "fat": 25},
    "ratings": {"mCZveucl60OQFTU0T8F5lsoY2mJ3": 5},
  },
  {
    "id": "r2",
    "title": "Avocado Toast with Egg",
    "description": "Quick, creamy avocado toast topped with poached eggs.",
    "instructions": [
      "Toast bread slices.",
      "Mash avocado with salt and lime juice.",
      "Spread avocado on toast.",
      "Top with poached egg and pepper.",
    ],
    "prep_time": 10,
    "cook_time": 5,
    "total_time": 15,
    "difficulty": "Easy",
    "servings": 2,
    "tags": ["Breakfast", "Healthy", "Quick"],
    "categories": ["Breakfast"],
    "ingredients": [
      {"name": "Bread slices", "quantity": 2, "unit": "pc", "optional": false},
      {"name": "Avocado", "quantity": 1, "unit": "pc", "optional": false},
      {"name": "Eggs", "quantity": 2, "unit": "pc", "optional": false},
      {"name": "Lime juice", "quantity": 1, "unit": "tsp", "optional": false},
    ],
    "image_urls": [
      "https://gratefulgrazer.com/wp-content/uploads/2025/01/avocado-toast-square.jpg, https://cdn11.bigcommerce.com/s-5ljyj9oebs/images/stencil/600x600/products/2794/36769/P060222144730_1__05187.1727119450.jpg?c=2",
    ],
    "created_by": "mCZveucl60OQFTU0T8F5lsoY2mJ3",
    "created_at": Timestamp.now(),
    "updated_at": Timestamp.now(),
  },
  {
    "id": "r3",
    "title": "Chicken Caesar Salad",
    "description":
        "Crisp romaine lettuce, grilled chicken, and creamy Caesar dressing.",
    "instructions": [
      "Grill chicken breasts and slice.",
      "Toss lettuce with Caesar dressing.",
      "Add croutons and parmesan.",
      "Top with chicken and serve.",
    ],
    "prep_time": 20,
    "cook_time": 15,
    "total_time": 35,
    "difficulty": "Easy",
    "servings": 3,
    "tags": ["Salad", "Healthy"],
    "categories": ["Lunch"],
    "ingredients": [
      {
        "name": "Romaine lettuce",
        "quantity": 1,
        "unit": "head",
        "optional": false,
      },
      {
        "name": "Chicken breast",
        "quantity": 300,
        "unit": "g",
        "optional": false,
      },
      {
        "name": "Parmesan cheese",
        "quantity": 50,
        "unit": "g",
        "optional": false,
      },
      {"name": "Croutons", "quantity": 50, "unit": "g", "optional": false},
    ],
    "image_urls": [
      "https://www.jessicagavin.com/wp-content/uploads/2022/06/chicken-caesar-salad-28-1200.jpg",
    ],
    "created_by": "PL6k0LQl0SWfz51gC93yR7Cv4X63",
    "created_at": Timestamp.now(),
    "updated_at": Timestamp.now(),
  },
  {
    "id": "r4",
    "title": "Beef Tacos",
    "description": "Spicy beef tacos with fresh toppings and soft tortillas.",
    "instructions": [
      "Cook beef with taco seasoning.",
      "Warm tortillas.",
      "Assemble tacos with beef, lettuce, tomato, and cheese.",
      "Serve with salsa.",
    ],
    "prep_time": 15,
    "cook_time": 20,
    "total_time": 35,
    "difficulty": "Easy",
    "servings": 4,
    "tags": ["Mexican", "Dinner", "Spicy"],
    "categories": ["Main Course"],
    "ingredients": [
      {"name": "Ground beef", "quantity": 500, "unit": "g", "optional": false},
      {
        "name": "Taco seasoning",
        "quantity": 2,
        "unit": "tbsp",
        "optional": false,
      },
      {"name": "Tortillas", "quantity": 8, "unit": "pc", "optional": false},
      {"name": "Lettuce", "quantity": 100, "unit": "g", "optional": false},
      {"name": "Tomato", "quantity": 2, "unit": "pc", "optional": false},
      {
        "name": "Cheddar cheese",
        "quantity": 100,
        "unit": "g",
        "optional": false,
      },
    ],
    "image_urls": [
      "https://media.istockphoto.com/id/1333647378/photo/homemade-american-soft-shell-beef-tacos.jpg?s=612x612&w=0&k=20&c=ZHhpFNbH_BO4MaXzmcKLjC4cPRptdXlp6IVUfs1sBEs=",
      "https://kaynutrition.com/wp-content/uploads/2023/08/shredded-beef-tacos.jpg",
    ],
    "created_by": "p75y1GigXochokLkpQuZ7NwuUe42",
    "created_at": Timestamp.now(),
    "updated_at": Timestamp.now(),
  },
  {
    "id": "r5",
    "title": "Fluffy Pancakes",
    "description": "Soft, fluffy pancakes perfect for breakfast.",
    "instructions": [
      "Mix flour, sugar, baking powder, and salt.",
      "Add milk, eggs, and melted butter.",
      "Cook on a greased skillet until golden brown.",
      "Serve with syrup and berries.",
    ],
    "prep_time": 10,
    "cook_time": 15,
    "total_time": 25,
    "difficulty": "Easy",
    "servings": 4,
    "tags": ["Breakfast", "Sweet", "Quick"],
    "categories": ["Breakfast"],
    "ingredients": [
      {"name": "Flour", "quantity": 200, "unit": "g", "optional": false},
      {"name": "Sugar", "quantity": 2, "unit": "tbsp", "optional": false},
      {
        "name": "Baking powder",
        "quantity": 2,
        "unit": "tsp",
        "optional": false,
      },
      {"name": "Salt", "quantity": 0.5, "unit": "tsp", "optional": false},
      {"name": "Milk", "quantity": 250, "unit": "ml", "optional": false},
      {"name": "Eggs", "quantity": 2, "unit": "pc", "optional": false},
      {"name": "Butter", "quantity": 30, "unit": "g", "optional": false},
    ],
    "image_urls": [
      "https://www.chocolatesandchai.com/wp-content/uploads/2018/07/Fluffy-Pancakes-Featured.jpg",
      "https://img.buzzfeed.com/video-api-prod/assets/948a9cec015e4ff7aef1d761c506ac05/PancakePinterest1.jpg",
    ],
    "created_by": "PL6k0LQl0SWfz51gC93yR7Cv4X63",
    "created_at": Timestamp.now(),
    "updated_at": Timestamp.now(),
  },
  {
    "id": "r6",
    "title": "Grilled Salmon",
    "description": "Perfectly grilled salmon fillets with lemon and herbs.",
    "instructions": [
      "Preheat grill to medium-high.",
      "Season salmon with salt, pepper, and lemon juice.",
      "Grill for 4–5 minutes per side.",
      "Serve with roasted vegetables.",
    ],
    "prep_time": 10,
    "cook_time": 10,
    "total_time": 20,
    "difficulty": "Medium",
    "servings": 2,
    "tags": ["Dinner", "Seafood", "Healthy"],
    "categories": ["Main Course"],
    "ingredients": [
      {
        "name": "Salmon fillets",
        "quantity": 2,
        "unit": "pc",
        "optional": false,
      },
      {"name": "Lemon juice", "quantity": 1, "unit": "tbsp", "optional": false},
      {"name": "Salt", "quantity": 0.5, "unit": "tsp", "optional": false},
      {
        "name": "Black pepper",
        "quantity": 0.5,
        "unit": "tsp",
        "optional": false,
      },
    ],
    "image_urls": [
      "https://images.services.kitchenstories.io/iVj59av0wHJY3TWq3Ym32RuJvyg=/3840x0/filters:quality(85)/images.kitchenstories.io/wagtailOriginalImages/R3022-final-photo-3.jpg",
      "https://thekitchengirl.com/wp-content/uploads/Grilled-Salmon-a_19-2.jpg",
    ],
    "created_by": "rJ2qT0v7AbXGkH4xE5yZ9cDfL8mQ",
    "created_at": Timestamp.now(),
    "updated_at": Timestamp.now(),
  },
  {
    "id": "r7",
    "title": "Vegetable Stir-Fry",
    "description": "Quick and healthy stir-fried vegetables with soy sauce.",
    "instructions": [
      "Chop all vegetables.",
      "Heat oil in a wok and stir-fry garlic.",
      "Add vegetables and stir-fry for 5–7 minutes.",
      "Add soy sauce and sesame oil, toss, and serve.",
    ],
    "prep_time": 10,
    "cook_time": 10,
    "total_time": 20,
    "difficulty": "Easy",
    "servings": 3,
    "tags": ["Vegan", "Quick", "Healthy"],
    "categories": ["Lunch", "Dinner"],
    "ingredients": [
      {"name": "Broccoli", "quantity": 100, "unit": "g", "optional": false},
      {"name": "Carrot", "quantity": 1, "unit": "pc", "optional": false},
      {"name": "Bell pepper", "quantity": 1, "unit": "pc", "optional": false},
      {"name": "Soy sauce", "quantity": 2, "unit": "tbsp", "optional": false},
      {"name": "Sesame oil", "quantity": 1, "unit": "tsp", "optional": false},
    ],
    "image_urls": [
      "https://www.allrecipes.com/thmb/MF7yU1MBbRlaT40ogVr-1PgggKc=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/222658-frozen-vegetable-stir-fry-4x3-1382-583b53fa0bcd4247920611ad431c14cb.jpg",
      "https://joyfoodsunshine.com/wp-content/uploads/2021/05/stir-fry-vegetables-recipe-8.jpg",
    ],
    "created_by": "U93js9QhWmdpaL8z0lF6bPtq1kP4",
    "created_at": Timestamp.now(),
    "updated_at": Timestamp.now(),
  },
  {
    "id": "r8",
    "title": "Chocolate Chip Cookies",
    "description": "Classic chewy chocolate chip cookies with a golden crust.",
    "instructions": [
      "Preheat oven to 180°C.",
      "Mix butter, sugar, and eggs.",
      "Add flour, baking soda, and chocolate chips.",
      "Scoop onto baking sheet and bake for 10–12 minutes.",
    ],
    "prep_time": 15,
    "cook_time": 12,
    "total_time": 27,
    "difficulty": "Easy",
    "servings": 24,
    "tags": ["Dessert", "Sweet", "Baking"],
    "categories": ["Dessert"],
    "ingredients": [
      {"name": "Flour", "quantity": 250, "unit": "g", "optional": false},
      {"name": "Sugar", "quantity": 150, "unit": "g", "optional": false},
      {"name": "Butter", "quantity": 125, "unit": "g", "optional": false},
      {"name": "Eggs", "quantity": 1, "unit": "pc", "optional": false},
      {
        "name": "Chocolate chips",
        "quantity": 150,
        "unit": "g",
        "optional": false,
      },
    ],
    "image_urls": [
      "https://handletheheat.com/wp-content/uploads/2020/10/BAKERY-STYLE-CHOCOLATE-CHIP-COOKIES-9-637x637-1-500x500.jpg",
      "https://cdn.loveandlemons.com/wp-content/uploads/2024/08/chocolate-chip-cookie-recipe.jpg",
    ],
    "created_by": "PL6k0LQl0SWfz51gC93yR7Cv4X63",
    "created_at": Timestamp.now(),
    "updated_at": Timestamp.now(),
  },
  {
    "id": "r9",
    "title": "Mango Smoothie",
    "description": "Refreshing mango smoothie, perfect for breakfast or snack.",
    "instructions": [
      "Peel and chop mango.",
      "Blend mango, yogurt, honey, and ice until smooth.",
      "Pour into glasses and serve.",
    ],
    "prep_time": 5,
    "cook_time": 0,
    "total_time": 5,
    "difficulty": "Easy",
    "servings": 2,
    "tags": ["Drink", "Healthy", "Quick"],
    "categories": ["Beverage"],
    "ingredients": [
      {"name": "Mango", "quantity": 1, "unit": "pc", "optional": false},
      {"name": "Yogurt", "quantity": 150, "unit": "ml", "optional": false},
      {"name": "Honey", "quantity": 1, "unit": "tbsp", "optional": false},
      {"name": "Ice cubes", "quantity": 4, "unit": "pc", "optional": true},
    ],
    "image_urls": [
      "https://cdn.loveandlemons.com/wp-content/uploads/opengraph/2023/05/mango-smoothie-recipe.jpg",
      "https://www.jessicagavin.com/wp-content/uploads/2020/06/mango-smoothie-7-1200.jpg",
    ],
    "created_by": "mCZveucl60OQFTU0T8F5lsoY2mJ3",
    "created_at": Timestamp.now(),
    "updated_at": Timestamp.now(),
  },
  {
    "id": "r10",
    "title": "Mushroom Risotto",
    "description": "Creamy risotto with mushrooms, garlic, and parmesan.",
    "instructions": [
      "Sauté mushrooms and garlic in olive oil.",
      "Add arborio rice and toast for 2 minutes.",
      "Gradually add vegetable stock while stirring.",
      "Once cooked, stir in parmesan and serve.",
    ],
    "prep_time": 15,
    "cook_time": 25,
    "total_time": 40,
    "difficulty": "Medium",
    "servings": 3,
    "tags": ["Italian", "Dinner", "Vegetarian"],
    "categories": ["Main Course"],
    "ingredients": [
      {"name": "Arborio rice", "quantity": 200, "unit": "g", "optional": false},
      {"name": "Mushrooms", "quantity": 150, "unit": "g", "optional": false},
      {"name": "Garlic cloves", "quantity": 2, "unit": "pc", "optional": false},
      {
        "name": "Parmesan cheese",
        "quantity": 50,
        "unit": "g",
        "optional": false,
      },
      {
        "name": "Vegetable stock",
        "quantity": 500,
        "unit": "ml",
        "optional": false,
      },
    ],
    "image_urls": [
      "https://hips.hearstapps.com/delish/assets/17/35/1504128527-delish-mushroom-risotto.jpg",
      "https://cdn77-s3.lazycatkitchen.com/wp-content/uploads/2019/11/vegan-mushroom-risotto-close-1000x1500.jpg",
    ],
    "created_by": "PL6k0LQl0SWfz51gC93yR7Cv4X63",
    "created_at": Timestamp.now(),
    "updated_at": Timestamp.now(),
  },
  // r4–r10: continue the same way with unique data (tacos, pancakes, cookies, stir-fry, smoothie, risotto, salmon)
];

final dummyUsers = [
  //testin user
  {
    "uid": "PL6k0LQl0SWfz51gC93yR7Cv4X63",
    "displayName": "Leo",
    "email": "laitho15@gmail.com",
    "photoUrl":
        "https://firebasestorage.googleapis.com/v0/b/recipe-book-e70cf.firebasestorage.app/o/user_profiles%2F1760066084695-p75y1GigXochokLkpQuZ7NwuUe42.jpg?alt=media&token=491e7a39-cb6b-4373-a9ef-a6ce0efb9eae",
    "followers": [
      "mCZveucl60OQFTU0T8F5lsoY2mJ3",
      "U93js9QhWmdpaL8z0lF6bPtq1kP4",
    ],
    "following": ["mCZveucl60OQFTU0T8F5lsoY2mJ3"],
    "favorites": ["r4", "r8", "r10"],
    "bio": "Passionate home chef creating comfort food with love ❤️",
    "created_at": Timestamp.now(),
    "updated_at": Timestamp.now(),
  },
  {
    "uid": "p75y1GigXochokLkpQuZ7NwuUe42",
    "displayName": "chef_amelia",
    "email": "amelia@recipes.com",
    "photoUrl": null,
    "followers": [
      "mCZveucl60OQFTU0T8F5lsoY2mJ3",
      "U93js9QhWmdpaL8z0lF6bPtq1kP4",
    ],
    "following": ["mCZveucl60OQFTU0T8F5lsoY2mJ3"],
    "favorites": ["r4", "r8", "r10"],
    "bio": "Passionate home chef creating comfort food with love ❤️",
    "created_at": Timestamp.now(),
    "updated_at": Timestamp.now(),
  },
  {
    "uid": "mCZveucl60OQFTU0T8F5lsoY2mJ3",
    "displayName": "leo_cooks",
    "email": "leo@greensense.dev",
    "photoUrl": null,
    "followers": [
      "p75y1GigXochokLkpQuZ7NwuUe42",
      "x27sDfN1pVRzYUc6gZr8eT3q8Lm9",
    ],
    "following": [
      "p75y1GigXochokLkpQuZ7NwuUe42",
      "U93js9QhWmdpaL8z0lF6bPtq1kP4",
    ],
    "favorites": ["r1", "r5", "r9"],
    "bio": "Cooking is art. Eat well, live better. 👨‍🍳",
    "created_at": Timestamp.now(),
    "updated_at": Timestamp.now(),
  },
  {
    "uid": "U93js9QhWmdpaL8z0lF6bPtq1kP4",
    "displayName": "vegan_vibes",
    "email": "vibes@plantlover.io",
    "photoUrl": null,
    "followers": ["p75y1GigXochokLkpQuZ7NwuUe42"],
    "following": ["mCZveucl60OQFTU0T8F5lsoY2mJ3"],
    "favorites": ["r7", "r9"],
    "bio": "🌱 Plant-based chef sharing cruelty-free flavors!",
    "created_at": Timestamp.now(),
    "updated_at": Timestamp.now(),
  },
  {
    "uid": "x27sDfN1pVRzYUc6gZr8eT3q8Lm9",
    "displayName": "bake_it_easy",
    "email": "bakeit@desserts.co",
    "photoUrl": null,
    "followers": ["mCZveucl60OQFTU0T8F5lsoY2mJ3"],
    "following": [
      "p75y1GigXochokLkpQuZ7NwuUe42",
      "U93js9QhWmdpaL8z0lF6bPtq1kP4",
    ],
    "favorites": ["r5", "r8"],
    "bio": "Dessert queen 🍰 | Baking joy one batch at a time",
    "created_at": Timestamp.now(),
    "updated_at": Timestamp.now(),
  },
  {
    "uid": "rJ2qT0v7AbXGkH4xE5yZ9cDfL8mQ",
    "displayName": "grill_master",
    "email": "grill@meatlovers.net",
    "photoUrl": null,
    "followers": ["x27sDfN1pVRzYUc6gZr8eT3q8Lm9"],
    "following": ["p75y1GigXochokLkpQuZ7NwuUe42"],
    "favorites": ["r1", "r6", "r4"],
    "bio": "🔥 BBQ lover & meat perfectionist — smoke, spice, repeat.",
    "created_at": Timestamp.now(),
    "updated_at": Timestamp.now(),
  },
];
